
package com.sahand.management.proxy.service.administration;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3.1-hudson-417-SNAPSHOT
 * Generated source version: 2.1
 * 
 */
@WebService(name = "UserAdministrationImpl", targetNamespace = "http://service.administration.industrial.sahand.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UserAdministrationImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.sahand.generalreport.services.administration.UserAdministrationRs
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addBranch", targetNamespace = "http://service.administration.industrial.sahand.com/", className = "com.sahand.generalreport.services.administration.AddBranch")
    @ResponseWrapper(localName = "addBranchResponse", targetNamespace = "http://service.administration.industrial.sahand.com/", className = "com.sahand.generalreport.services.administration.AddBranchResponse")
    public UserAdministrationRs addBranch(
        @WebParam(name = "arg0", targetNamespace = "")
        UserAdministrationRq arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.sahand.generalreport.services.administration.UserAdministrationRs
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addBranchEmployee", targetNamespace = "http://service.administration.industrial.sahand.com/", className = "com.sahand.generalreport.services.administration.AddBranchEmployee")
    @ResponseWrapper(localName = "addBranchEmployeeResponse", targetNamespace = "http://service.administration.industrial.sahand.com/", className = "com.sahand.generalreport.services.administration.AddBranchEmployeeResponse")
    public UserAdministrationRs addBranchEmployee(
        @WebParam(name = "arg0", targetNamespace = "")
        UserAdministrationRq arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.sahand.generalreport.services.administration.UserAdministrationRs
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addBranchInventory", targetNamespace = "http://service.administration.industrial.sahand.com/", className = "com.sahand.generalreport.services.administration.AddBranchInventory")
    @ResponseWrapper(localName = "addBranchInventoryResponse", targetNamespace = "http://service.administration.industrial.sahand.com/", className = "com.sahand.generalreport.services.administration.AddBranchInventoryResponse")
    public UserAdministrationRs addBranchInventory(
        @WebParam(name = "arg0", targetNamespace = "")
        UserAdministrationRq arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.sahand.generalreport.services.administration.UserAdministrationRs
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addGroupValidTransaction", targetNamespace = "http://service.administration.industrial.sahand.com/", className = "com.sahand.generalreport.services.administration.AddGroupValidTransaction")
    @ResponseWrapper(localName = "addGroupValidTransactionResponse", targetNamespace = "http://service.administration.industrial.sahand.com/", className = "com.sahand.generalreport.services.administration.AddGroupValidTransactionResponse")
    public UserAdministrationRs addGroupValidTransaction(
        @WebParam(name = "arg0", targetNamespace = "")
        UserAdministrationRq arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.sahand.generalreport.services.administration.UserAdministrationRs
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addNewGroup", targetNamespace = "http://service.administration.industrial.sahand.com/", className = "com.sahand.generalreport.services.administration.AddNewGroup")
    @ResponseWrapper(localName = "addNewGroupResponse", targetNamespace = "http://service.administration.industrial.sahand.com/", className = "com.sahand.generalreport.services.administration.AddNewGroupResponse")
    public UserAdministrationRs addNewGroup(
        @WebParam(name = "arg0", targetNamespace = "")
        UserAdministrationRq arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.sahand.generalreport.services.administration.UserAdministrationRs
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addNewUser", targetNamespace = "http://service.administration.industrial.sahand.com/", className = "com.sahand.generalreport.services.administration.AddNewUser")
    @ResponseWrapper(localName = "addNewUserResponse", targetNamespace = "http://service.administration.industrial.sahand.com/", className = "com.sahand.generalreport.services.administration.AddNewUserResponse")
    public UserAdministrationRs addNewUser(
        @WebParam(name = "arg0", targetNamespace = "")
        UserAdministrationRq arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.sahand.generalreport.services.administration.UserAdministrationRs
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "assignUIComp2Group", targetNamespace = "http://service.administration.industrial.sahand.com/", className = "com.sahand.generalreport.services.administration.AssignUIComp2Group")
    @ResponseWrapper(localName = "assignUIComp2GroupResponse", targetNamespace = "http://service.administration.industrial.sahand.com/", className = "com.sahand.generalreport.services.administration.AssignUIComp2GroupResponse")
    public UserAdministrationRs assignUIComp2Group(
        @WebParam(name = "arg0", targetNamespace = "")
        UserAdministrationRq arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.sahand.generalreport.services.administration.UserAdministrationRs
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "assignUICompSystemAction2Group", targetNamespace = "http://service.administration.industrial.sahand.com/", className = "com.sahand.generalreport.services.administration.AssignUICompSystemAction2Group")
    @ResponseWrapper(localName = "assignUICompSystemAction2GroupResponse", targetNamespace = "http://service.administration.industrial.sahand.com/", className = "com.sahand.generalreport.services.administration.AssignUICompSystemAction2GroupResponse")
    public UserAdministrationRs assignUICompSystemAction2Group(
        @WebParam(name = "arg0", targetNamespace = "")
        UserAdministrationRq arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.sahand.generalreport.services.administration.UserAdministrationRs
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "assignUser2Group", targetNamespace = "http://service.administration.industrial.sahand.com/", className = "com.sahand.generalreport.services.administration.AssignUser2Group")
    @ResponseWrapper(localName = "assignUser2GroupResponse", targetNamespace = "http://service.administration.industrial.sahand.com/", className = "com.sahand.generalreport.services.administration.AssignUser2GroupResponse")
    public UserAdministrationRs assignUser2Group(
        @WebParam(name = "arg0", targetNamespace = "")
        UserAdministrationRq arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.sahand.generalreport.services.administration.UserAdministrationRs
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "changeUserPassword", targetNamespace = "http://service.administration.industrial.sahand.com/", className = "com.sahand.generalreport.services.administration.ChangeUserPassword")
    @ResponseWrapper(localName = "changeUserPasswordResponse", targetNamespace = "http://service.administration.industrial.sahand.com/", className = "com.sahand.generalreport.services.administration.ChangeUserPasswordResponse")
    public UserAdministrationRs changeUserPassword(
        @WebParam(name = "arg0", targetNamespace = "")
        UserAdministrationRq arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.sahand.generalreport.services.administration.UserAdministrationRs
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "changeUserState", targetNamespace = "http://service.administration.industrial.sahand.com/", className = "com.sahand.generalreport.services.administration.ChangeUserState")
    @ResponseWrapper(localName = "changeUserStateResponse", targetNamespace = "http://service.administration.industrial.sahand.com/", className = "com.sahand.generalreport.services.administration.ChangeUserStateResponse")
    public UserAdministrationRs changeUserState(
        @WebParam(name = "arg0", targetNamespace = "")
        UserAdministrationRq arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.sahand.generalreport.services.administration.UserAdministrationRs
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "defineExceptionDate", targetNamespace = "http://service.administration.industrial.sahand.com/", className = "com.sahand.generalreport.services.administration.DefineExceptionDate")
    @ResponseWrapper(localName = "defineExceptionDateResponse", targetNamespace = "http://service.administration.industrial.sahand.com/", className = "com.sahand.generalreport.services.administration.DefineExceptionDateResponse")
    public UserAdministrationRs defineExceptionDate(
        @WebParam(name = "arg0", targetNamespace = "")
        UserAdministrationRq arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.sahand.generalreport.services.administration.UserAdministrationRs
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "defineSystemAction", targetNamespace = "http://service.administration.industrial.sahand.com/", className = "com.sahand.generalreport.services.administration.DefineSystemAction")
    @ResponseWrapper(localName = "defineSystemActionResponse", targetNamespace = "http://service.administration.industrial.sahand.com/", className = "com.sahand.generalreport.services.administration.DefineSystemActionResponse")
    public UserAdministrationRs defineSystemAction(
        @WebParam(name = "arg0", targetNamespace = "")
        UserAdministrationRq arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.sahand.generalreport.services.administration.UserAdministrationRs
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBranchEmployeeList", targetNamespace = "http://service.administration.industrial.sahand.com/", className = "com.sahand.generalreport.services.administration.GetBranchEmployeeList")
    @ResponseWrapper(localName = "getBranchEmployeeListResponse", targetNamespace = "http://service.administration.industrial.sahand.com/", className = "com.sahand.generalreport.services.administration.GetBranchEmployeeListResponse")
    public UserAdministrationRs getBranchEmployeeList(
        @WebParam(name = "arg0", targetNamespace = "")
        UserAdministrationRq arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.sahand.generalreport.services.administration.UserAdministrationRs
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBranchList", targetNamespace = "http://service.administration.industrial.sahand.com/", className = "com.sahand.generalreport.services.administration.GetBranchList")
    @ResponseWrapper(localName = "getBranchListResponse", targetNamespace = "http://service.administration.industrial.sahand.com/", className = "com.sahand.generalreport.services.administration.GetBranchListResponse")
    public UserAdministrationRs getBranchList(
        @WebParam(name = "arg0", targetNamespace = "")
        UserAdministrationRq arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.sahand.generalreport.services.administration.UserAdministrationRs
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBranchListInventory", targetNamespace = "http://service.administration.industrial.sahand.com/", className = "com.sahand.generalreport.services.administration.GetBranchListInventory")
    @ResponseWrapper(localName = "getBranchListInventoryResponse", targetNamespace = "http://service.administration.industrial.sahand.com/", className = "com.sahand.generalreport.services.administration.GetBranchListInventoryResponse")
    public UserAdministrationRs getBranchListInventory(
        @WebParam(name = "arg0", targetNamespace = "")
        UserAdministrationRq arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.sahand.generalreport.services.administration.UserAdministrationRs
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getExceptionDateList", targetNamespace = "http://service.administration.industrial.sahand.com/", className = "com.sahand.generalreport.services.administration.GetExceptionDateList")
    @ResponseWrapper(localName = "getExceptionDateListResponse", targetNamespace = "http://service.administration.industrial.sahand.com/", className = "com.sahand.generalreport.services.administration.GetExceptionDateListResponse")
    public UserAdministrationRs getExceptionDateList(
        @WebParam(name = "arg0", targetNamespace = "")
        UserAdministrationRq arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.sahand.generalreport.services.administration.UserAdministrationRs
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getExceptionDateListFull", targetNamespace = "http://service.administration.industrial.sahand.com/", className = "com.sahand.generalreport.services.administration.GetExceptionDateListFull")
    @ResponseWrapper(localName = "getExceptionDateListFullResponse", targetNamespace = "http://service.administration.industrial.sahand.com/", className = "com.sahand.generalreport.services.administration.GetExceptionDateListFullResponse")
    public UserAdministrationRs getExceptionDateListFull(
        @WebParam(name = "arg0", targetNamespace = "")
        UserAdministrationRq arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.sahand.generalreport.services.administration.UserAdministrationRs
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getGroupInValidActionList", targetNamespace = "http://service.administration.industrial.sahand.com/", className = "com.sahand.generalreport.services.administration.GetGroupInValidActionList")
    @ResponseWrapper(localName = "getGroupInValidActionListResponse", targetNamespace = "http://service.administration.industrial.sahand.com/", className = "com.sahand.generalreport.services.administration.GetGroupInValidActionListResponse")
    public UserAdministrationRs getGroupInValidActionList(
        @WebParam(name = "arg0", targetNamespace = "")
        UserAdministrationRq arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.sahand.generalreport.services.administration.UserAdministrationRs
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getGroupList", targetNamespace = "http://service.administration.industrial.sahand.com/", className = "com.sahand.generalreport.services.administration.GetGroupList")
    @ResponseWrapper(localName = "getGroupListResponse", targetNamespace = "http://service.administration.industrial.sahand.com/", className = "com.sahand.generalreport.services.administration.GetGroupListResponse")
    public UserAdministrationRs getGroupList(
        @WebParam(name = "arg0", targetNamespace = "")
        UserAdministrationRq arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.sahand.generalreport.services.administration.UserAdministrationRs
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getGroupMembers", targetNamespace = "http://service.administration.industrial.sahand.com/", className = "com.sahand.generalreport.services.administration.GetGroupMembers")
    @ResponseWrapper(localName = "getGroupMembersResponse", targetNamespace = "http://service.administration.industrial.sahand.com/", className = "com.sahand.generalreport.services.administration.GetGroupMembersResponse")
    public UserAdministrationRs getGroupMembers(
        @WebParam(name = "arg0", targetNamespace = "")
        UserAdministrationRq arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.sahand.generalreport.services.administration.UserAdministrationRs
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getGroupNoneMembers", targetNamespace = "http://service.administration.industrial.sahand.com/", className = "com.sahand.generalreport.services.administration.GetGroupNoneMembers")
    @ResponseWrapper(localName = "getGroupNoneMembersResponse", targetNamespace = "http://service.administration.industrial.sahand.com/", className = "com.sahand.generalreport.services.administration.GetGroupNoneMembersResponse")
    public UserAdministrationRs getGroupNoneMembers(
        @WebParam(name = "arg0", targetNamespace = "")
        UserAdministrationRq arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.sahand.generalreport.services.administration.UserAdministrationRs
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getGroupUIComponents", targetNamespace = "http://service.administration.industrial.sahand.com/", className = "com.sahand.generalreport.services.administration.GetGroupUIComponents")
    @ResponseWrapper(localName = "getGroupUIComponentsResponse", targetNamespace = "http://service.administration.industrial.sahand.com/", className = "com.sahand.generalreport.services.administration.GetGroupUIComponentsResponse")
    public UserAdministrationRs getGroupUIComponents(
        @WebParam(name = "arg0", targetNamespace = "")
        UserAdministrationRq arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.sahand.generalreport.services.administration.UserAdministrationRs
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getGroupValidActionList", targetNamespace = "http://service.administration.industrial.sahand.com/", className = "com.sahand.generalreport.services.administration.GetGroupValidActionList")
    @ResponseWrapper(localName = "getGroupValidActionListResponse", targetNamespace = "http://service.administration.industrial.sahand.com/", className = "com.sahand.generalreport.services.administration.GetGroupValidActionListResponse")
    public UserAdministrationRs getGroupValidActionList(
        @WebParam(name = "arg0", targetNamespace = "")
        UserAdministrationRq arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.sahand.generalreport.services.administration.UserAdministrationRs
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSystemActionList", targetNamespace = "http://service.administration.industrial.sahand.com/", className = "com.sahand.generalreport.services.administration.GetSystemActionList")
    @ResponseWrapper(localName = "getSystemActionListResponse", targetNamespace = "http://service.administration.industrial.sahand.com/", className = "com.sahand.generalreport.services.administration.GetSystemActionListResponse")
    public UserAdministrationRs getSystemActionList(
        @WebParam(name = "arg0", targetNamespace = "")
        UserAdministrationRq arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.sahand.generalreport.services.administration.UserAdministrationRs
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUIComponentTree", targetNamespace = "http://service.administration.industrial.sahand.com/", className = "com.sahand.generalreport.services.administration.GetUIComponentTree")
    @ResponseWrapper(localName = "getUIComponentTreeResponse", targetNamespace = "http://service.administration.industrial.sahand.com/", className = "com.sahand.generalreport.services.administration.GetUIComponentTreeResponse")
    public UserAdministrationRs getUIComponentTree(
        @WebParam(name = "arg0", targetNamespace = "")
        UserAdministrationRq arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.sahand.generalreport.services.administration.UserAdministrationRs
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUserList", targetNamespace = "http://service.administration.industrial.sahand.com/", className = "com.sahand.generalreport.services.administration.GetUserList")
    @ResponseWrapper(localName = "getUserListResponse", targetNamespace = "http://service.administration.industrial.sahand.com/", className = "com.sahand.generalreport.services.administration.GetUserListResponse")
    public UserAdministrationRs getUserList(
        @WebParam(name = "arg0", targetNamespace = "")
        UserAdministrationRq arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.sahand.generalreport.services.administration.UserAdministrationRs
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUserMembership", targetNamespace = "http://service.administration.industrial.sahand.com/", className = "com.sahand.generalreport.services.administration.GetUserMembership")
    @ResponseWrapper(localName = "getUserMembershipResponse", targetNamespace = "http://service.administration.industrial.sahand.com/", className = "com.sahand.generalreport.services.administration.GetUserMembershipResponse")
    public UserAdministrationRs getUserMembership(
        @WebParam(name = "arg0", targetNamespace = "")
        UserAdministrationRq arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.sahand.generalreport.services.administration.UserAdministrationRs
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "modifyBranch", targetNamespace = "http://service.administration.industrial.sahand.com/", className = "com.sahand.generalreport.services.administration.ModifyBranch")
    @ResponseWrapper(localName = "modifyBranchResponse", targetNamespace = "http://service.administration.industrial.sahand.com/", className = "com.sahand.generalreport.services.administration.ModifyBranchResponse")
    public UserAdministrationRs modifyBranch(
        @WebParam(name = "arg0", targetNamespace = "")
        UserAdministrationRq arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.sahand.generalreport.services.administration.UserAdministrationRs
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "modifyBranchInventory", targetNamespace = "http://service.administration.industrial.sahand.com/", className = "com.sahand.generalreport.services.administration.ModifyBranchInventory")
    @ResponseWrapper(localName = "modifyBranchInventoryResponse", targetNamespace = "http://service.administration.industrial.sahand.com/", className = "com.sahand.generalreport.services.administration.ModifyBranchInventoryResponse")
    public UserAdministrationRs modifyBranchInventory(
        @WebParam(name = "arg0", targetNamespace = "")
        UserAdministrationRq arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.sahand.generalreport.services.administration.UserAdministrationRs
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "modifyExceptionDate", targetNamespace = "http://service.administration.industrial.sahand.com/", className = "com.sahand.generalreport.services.administration.ModifyExceptionDate")
    @ResponseWrapper(localName = "modifyExceptionDateResponse", targetNamespace = "http://service.administration.industrial.sahand.com/", className = "com.sahand.generalreport.services.administration.ModifyExceptionDateResponse")
    public UserAdministrationRs modifyExceptionDate(
        @WebParam(name = "arg0", targetNamespace = "")
        UserAdministrationRq arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.sahand.generalreport.services.administration.UserAdministrationRs
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "modifyGroup", targetNamespace = "http://service.administration.industrial.sahand.com/", className = "com.sahand.generalreport.services.administration.ModifyGroup")
    @ResponseWrapper(localName = "modifyGroupResponse", targetNamespace = "http://service.administration.industrial.sahand.com/", className = "com.sahand.generalreport.services.administration.ModifyGroupResponse")
    public UserAdministrationRs modifyGroup(
        @WebParam(name = "arg0", targetNamespace = "")
        UserAdministrationRq arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.sahand.generalreport.services.administration.UserAdministrationRs
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "modifyUser", targetNamespace = "http://service.administration.industrial.sahand.com/", className = "com.sahand.generalreport.services.administration.ModifyUser")
    @ResponseWrapper(localName = "modifyUserResponse", targetNamespace = "http://service.administration.industrial.sahand.com/", className = "com.sahand.generalreport.services.administration.ModifyUserResponse")
    public UserAdministrationRs modifyUser(
        @WebParam(name = "arg0", targetNamespace = "")
        UserAdministrationRq arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.sahand.generalreport.services.administration.UserAdministrationRs
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "removeBranch", targetNamespace = "http://service.administration.industrial.sahand.com/", className = "com.sahand.generalreport.services.administration.RemoveBranch")
    @ResponseWrapper(localName = "removeBranchResponse", targetNamespace = "http://service.administration.industrial.sahand.com/", className = "com.sahand.generalreport.services.administration.RemoveBranchResponse")
    public UserAdministrationRs removeBranch(
        @WebParam(name = "arg0", targetNamespace = "")
        UserAdministrationRq arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.sahand.generalreport.services.administration.UserAdministrationRs
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "removeBranchEmployee", targetNamespace = "http://service.administration.industrial.sahand.com/", className = "com.sahand.generalreport.services.administration.RemoveBranchEmployee")
    @ResponseWrapper(localName = "removeBranchEmployeeResponse", targetNamespace = "http://service.administration.industrial.sahand.com/", className = "com.sahand.generalreport.services.administration.RemoveBranchEmployeeResponse")
    public UserAdministrationRs removeBranchEmployee(
        @WebParam(name = "arg0", targetNamespace = "")
        UserAdministrationRq arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.sahand.generalreport.services.administration.UserAdministrationRs
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "removeBranchInventory", targetNamespace = "http://service.administration.industrial.sahand.com/", className = "com.sahand.generalreport.services.administration.RemoveBranchInventory")
    @ResponseWrapper(localName = "removeBranchInventoryResponse", targetNamespace = "http://service.administration.industrial.sahand.com/", className = "com.sahand.generalreport.services.administration.RemoveBranchInventoryResponse")
    public UserAdministrationRs removeBranchInventory(
        @WebParam(name = "arg0", targetNamespace = "")
        UserAdministrationRq arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.sahand.generalreport.services.administration.UserAdministrationRs
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "removeExceptionDate", targetNamespace = "http://service.administration.industrial.sahand.com/", className = "com.sahand.generalreport.services.administration.RemoveExceptionDate")
    @ResponseWrapper(localName = "removeExceptionDateResponse", targetNamespace = "http://service.administration.industrial.sahand.com/", className = "com.sahand.generalreport.services.administration.RemoveExceptionDateResponse")
    public UserAdministrationRs removeExceptionDate(
        @WebParam(name = "arg0", targetNamespace = "")
        UserAdministrationRq arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.sahand.generalreport.services.administration.UserAdministrationRs
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "removeGroup", targetNamespace = "http://service.administration.industrial.sahand.com/", className = "com.sahand.generalreport.services.administration.RemoveGroup")
    @ResponseWrapper(localName = "removeGroupResponse", targetNamespace = "http://service.administration.industrial.sahand.com/", className = "com.sahand.generalreport.services.administration.RemoveGroupResponse")
    public UserAdministrationRs removeGroup(
        @WebParam(name = "arg0", targetNamespace = "")
        UserAdministrationRq arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.sahand.generalreport.services.administration.UserAdministrationRs
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "removeGroupvalidTransaction", targetNamespace = "http://service.administration.industrial.sahand.com/", className = "com.sahand.generalreport.services.administration.RemoveGroupvalidTransaction")
    @ResponseWrapper(localName = "removeGroupvalidTransactionResponse", targetNamespace = "http://service.administration.industrial.sahand.com/", className = "com.sahand.generalreport.services.administration.RemoveGroupvalidTransactionResponse")
    public UserAdministrationRs removeGroupvalidTransaction(
        @WebParam(name = "arg0", targetNamespace = "")
        UserAdministrationRq arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.sahand.generalreport.services.administration.UserAdministrationRs
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "removeUser", targetNamespace = "http://service.administration.industrial.sahand.com/", className = "com.sahand.generalreport.services.administration.RemoveUser")
    @ResponseWrapper(localName = "removeUserResponse", targetNamespace = "http://service.administration.industrial.sahand.com/", className = "com.sahand.generalreport.services.administration.RemoveUserResponse")
    public UserAdministrationRs removeUser(
        @WebParam(name = "arg0", targetNamespace = "")
        UserAdministrationRq arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.sahand.generalreport.services.administration.UserAdministrationRs
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "unassignUIComp2Group", targetNamespace = "http://service.administration.industrial.sahand.com/", className = "com.sahand.generalreport.services.administration.UnassignUIComp2Group")
    @ResponseWrapper(localName = "unassignUIComp2GroupResponse", targetNamespace = "http://service.administration.industrial.sahand.com/", className = "com.sahand.generalreport.services.administration.UnassignUIComp2GroupResponse")
    public UserAdministrationRs unassignUIComp2Group(
        @WebParam(name = "arg0", targetNamespace = "")
        UserAdministrationRq arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.sahand.generalreport.services.administration.UserAdministrationRs
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "unassignUICompSystemAction2Group", targetNamespace = "http://service.administration.industrial.sahand.com/", className = "com.sahand.generalreport.services.administration.UnassignUICompSystemAction2Group")
    @ResponseWrapper(localName = "unassignUICompSystemAction2GroupResponse", targetNamespace = "http://service.administration.industrial.sahand.com/", className = "com.sahand.generalreport.services.administration.UnassignUICompSystemAction2GroupResponse")
    public UserAdministrationRs unassignUICompSystemAction2Group(
        @WebParam(name = "arg0", targetNamespace = "")
        UserAdministrationRq arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.sahand.generalreport.services.administration.UserAdministrationRs
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "unassignUser2Group", targetNamespace = "http://service.administration.industrial.sahand.com/", className = "com.sahand.generalreport.services.administration.UnassignUser2Group")
    @ResponseWrapper(localName = "unassignUser2GroupResponse", targetNamespace = "http://service.administration.industrial.sahand.com/", className = "com.sahand.generalreport.services.administration.UnassignUser2GroupResponse")
    public UserAdministrationRs unassignUser2Group(
        @WebParam(name = "arg0", targetNamespace = "")
        UserAdministrationRq arg0);

}
